blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/WebDevSimplified/wds-shadcn-registry/discussions/new?category=q-a
    about: If you can't get something to work the way you expect, open a question in our discussion forums.
